### ISSUE TITLE
RAW code

### ISSUE THREAD

**Issue by maiiikell1995** [dudanov/MideaUART#1]
Hi, 

Sorry to create an issue which is not really an issue. 
I'm looking for the raw IR commands for a Mobile Coffee AC. 
I thought since your created this you should have them or at least some way of generating them.
Long story short id like to have those to create a HomeKit compatible IR Blaster.
I'm looking everywhere for them but couldn't find any on the web or other projects. 

Any help is appreciated

please feel free to close this issue since it not really an issue

**Comment by dudanov** [comment]
Hi

You can contact with David @crankyoldgit, who is leading a wonderful project [IRremoteESP8266](https://github.com/crankyoldgit/IRremoteESP8266). His experience is clearly a thousand times greater than mine. I think he can help you.
