### ISSUE TITLE
Question around heat pump state info

### ISSUE THREAD

**Issue by rdubya16** [dudanov/MideaUART#2]
Not sure if this is the best place to ask, but was wondering if the UART interface offers any additional information than what is exposed here? 

Mainly I was wondering if there is any state information about the compressor. This seems to expose that the heat pump is in heat mode but is there anything to indicate its defrosting or the level at which the compressor is operating?

**Comment by dudanov** [comment]
Sorry for such a long answer. To date, it is not known whether it is possible to receive the status of the compressor via UART. The protocol is proprietary, and has been researched by enthusiasts while working through official applications that do not display compressor status.
